[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
day10_escrow_anchor = "GWHDeVEboCXJfKZyuZuKX3omooMYYjMXs9SdRYa7HVNB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/local-wallet.json"

[scripts]
skip_deploy = "true"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
